### ISSUE TITLE
Radio Settings -> Radio Setup -> Model quick select

### ISSUE THREAD

**Issue by LevYas** [EdgeTX/edgetx-user-manual#12]
Hi, it's very nice to see such a neat approach to docs!

Yesterday I updated to 2.8.2 from 2.7, browsed through the menus, and found a setting, which is not explained anywhere.

Color radios (RM TX16s in my case) -> Radio Settings -> Radio Setup -> Model quick select

What does this setting mean?

**Comment by phileville** [comment]
Yes, that seems to be the PR that made this change. I plan to update the user manual once the 2.9 release candidate is published (and there should not be any further changes) with all the changes since 2.8 was released.  If in the meantime, you want to create a PR for this, then please feel free to do so. Thanks for pointing this out to me.
